# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  review_status: true
  path_filters:
    - '!apps/web/tests/**'
    - '!packages/motion-gpu/e2e/**'
    - '!packages/motion-gpu/src/tests/**'
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - master
